#include "graphics_controls_manual_data.h"

const HelpLine kControlsManual[] = {

    {HelpLineType::SECTION, "Welcome to Raising Hell"},
    {HelpLineType::BODY, "Thank you for playing"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Basic Controls"},
    {HelpLineType::BODY, "LEFT/RIGHT  Switch tabs"},
    {HelpLineType::BODY, "UP/DOWN     Move selection"},
    {HelpLineType::BODY, "ENTER/G     Confirm / interact"},
    {HelpLineType::BODY, "DEL/Q       Back / home"},
    {HelpLineType::BODY, "ESC       Open Settings / cancel"},
    {HelpLineType::BODY, "Z-M         Jump to tab"},
    {HelpLineType::BODY, "P           Take photo"},
    {HelpLineType::BODY, "GO          Toggle screen on/off"},
    {HelpLineType::BODY, "Shake       Wake screen"},
    {HelpLineType::BODY, "\\           Console"},
    {HelpLineType::GAP, nullptr},
    {HelpLineType::BODY, "Shake the device to wake screen"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Alt Navigation Clusters"},
    {HelpLineType::BODY, "(E A S D) and (O J K L)"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Congratulations!!"},
    {HelpLineType::BODY, "You summoned something from"},
    {HelpLineType::BODY, "beyond our mortal plane."},
    {HelpLineType::BODY, "Now it's your problem!!"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Care for Your Pet"},
    {HelpLineType::BODY, "Your Pet needs care!"},
    {HelpLineType::BODY, "Take this very seriously"},
    {HelpLineType::BODY, "You have been warned!"},
    {HelpLineType::BODY, "If your pet dies, nothing short"},
    {HelpLineType::BODY, "of apocalypse will bring it"},
    {HelpLineType::BODY, "back to life."},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Stats"},
    {HelpLineType::BODY, "Keep the bars full, or else!"},
    {HelpLineType::BODY, "Feed when hunger bar is low"},
    {HelpLineType::BODY, "Play when mood bar is low"},
    {HelpLineType::BODY, "Sleep when rest bar is low"},
    {HelpLineType::BODY, "If your pet is hungry for a"},
    {HelpLineType::BODY, "while, it will start to lose HP"},
    {HelpLineType::BODY, "soon it will die."},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Alerts"},
    {HelpLineType::BODY, "Red - Pet is in danger"},
    {HelpLineType::BODY, "Orange - Pet needs attention"},
    {HelpLineType::BODY, "Green - Pet is doing well"},
    {HelpLineType::BODY, "Blue - Warwalking Hit"},
    {HelpLineType::BODY, "If the screen is off, alerts"},
    {HelpLineType::BODY, "will briefly light it up."},
    {HelpLineType::BODY, "Heed these warnings or else!"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Death and Resurrection"},
    {HelpLineType::BODY, "Death is not the end for your"},
    {HelpLineType::BODY, "creature from beyond. Rip"},
    {HelpLineType::BODY, "your companion from the jaws of"},
    {HelpLineType::BODY, "death by completing a ritual"},
    {HelpLineType::BODY, "or commend it to the dirt and"},
    {HelpLineType::BODY, "face the consequences!"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Activities and Fishing"},
    {HelpLineType::BODY, "Activities give your pet more"},
    {HelpLineType::BODY, "ways to pass the time."},
    {HelpLineType::BODY, "Go fishing to spend bait and"},
    {HelpLineType::BODY, "try to catch something strange."},
    {HelpLineType::BODY, "Wait for a bite, then mash"},
    {HelpLineType::BODY, "ENTER to reel it in."},
    {HelpLineType::BODY, "The water remembers everything."},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Mini Games"},
    {HelpLineType::BODY, "Play mini games to earn cash"},
    {HelpLineType::BODY, "XP, and valuable prizes. Keep"},
    {HelpLineType::BODY, "your pet amused, keep it happy."},
    {HelpLineType::BODY, "Else your world is forfeit."},
    {HelpLineType::BODY, "Your otherworldly ward will"},
    {HelpLineType::BODY, "Soon grow tired of these games"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "War Walking"},
    {HelpLineType::BODY, "Carry your device in the real"},
    {HelpLineType::BODY, "world to uncover hidden signals."},
    {HelpLineType::BODY, "While idle or asleep, your steps"},
    {HelpLineType::BODY, "are tracked automatically."},
    {HelpLineType::BODY, "Movement may reveal rewards"},
    {HelpLineType::BODY, "such as Inferium or rare items."},
    {HelpLineType::GAP, nullptr},
    {HelpLineType::BODY, "These signals are not real."},
    {HelpLineType::BODY, "They are from beyond the void."},
    {HelpLineType::GAP, nullptr},
    {HelpLineType::BODY, "Enable Step Counter in Game"},
    {HelpLineType::BODY, "Options to view daily steps."},
    {HelpLineType::BODY, "You can reset the counter"},
    {HelpLineType::BODY, "manually from Game Options."},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Sleep"},
    {HelpLineType::BODY, "Even the spawm of evil needs"},
    {HelpLineType::BODY, "sleep. When your pet is tired"},
    {HelpLineType::BODY, "it won't play any games."},
    {HelpLineType::BODY, "Tuck your beast into bed to"},
    {HelpLineType::BODY, "recover energy, or use one of"},
    {HelpLineType::BODY, "the cursed items in the shop!"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Currency and Items"},
    {HelpLineType::BODY, "Inferium is the currency of"},
    {HelpLineType::BODY, "the underworld. It can be used"},
    {HelpLineType::BODY, "to buy food, cursed items, and"},
    {HelpLineType::BODY, "other mysterious artifacts"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "XP, Levels, and Evolution"},
    {HelpLineType::BODY, "Play Mini Games to Earn XP."},
    {HelpLineType::BODY, "XP will make your pet level up!"},
    {HelpLineType::BODY, "Level up enough, and your pet"},
    {HelpLineType::BODY, "can evolve! Who knows what"},
    {HelpLineType::BODY, "abominations you will nurture!"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Return to Baby"},
    {HelpLineType::BODY, "If your pet has evolved too far,"},
    {HelpLineType::BODY, "you may return it to baby form"},
    {HelpLineType::BODY, "from the menu."},
    {HelpLineType::BODY, "This keeps your pet, but resets"},
    {HelpLineType::BODY, "its evolution stage."},
    {HelpLineType::BODY, "Some powers are best kept small."},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Passive XP"},
    {HelpLineType::BODY, "Your pet gains XP over time,"},
    {HelpLineType::BODY, "even when you are not playing."},
    {HelpLineType::BODY, "Remain active, stay alive, and"},
    {HelpLineType::BODY, "the growth will come."},
    {HelpLineType::GAP, nullptr},
    {HelpLineType::BODY, "Sleeping, wandering, and idle"},
    {HelpLineType::BODY, "states all contribute to slow"},
    {HelpLineType::BODY, "but steady progression."},
    {HelpLineType::GAP, nullptr},
    {HelpLineType::BODY, "Neglect your pet, and this"},
    {HelpLineType::BODY, "growth may slow or stop."},
    {HelpLineType::BODY, "Suffering does not inspire."},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Multiple Pets!"},
    {HelpLineType::BODY, "If one pet is not enough, you"},
    {HelpLineType::BODY, "can have all the pets you want!"},
    {HelpLineType::BODY, "Simply store the pet in the menu."},
    {HelpLineType::BODY, "You are then free to hatch a new"},
    {HelpLineType::BODY, "creature. You can recall stored"},
    {HelpLineType::BODY, "pets at any time."},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Clock Mode!"},
    {HelpLineType::BODY, "Time is ticking, the end is near."},
    {HelpLineType::BODY, "You cannot stop it, but you can"},
    {HelpLineType::BODY, "watch it happen. Use clock mode!"},
    {HelpLineType::BODY, "available in the settings menu"},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Photos and Album"},
    {HelpLineType::BODY, "Press P to take a photo of"},
    {HelpLineType::BODY, "the current game screen."},
    {HelpLineType::BODY, "Photos are saved to your album"},
    {HelpLineType::BODY, "where you can view them later."},
    {HelpLineType::BODY, "Capture the creature. Capture"},
    {HelpLineType::BODY, "the evidence."},
    {HelpLineType::GAP, nullptr},

    {HelpLineType::SECTION, "Raising Hell"},
    {HelpLineType::BODY, "Made by: Aaron Ayers"},
    {HelpLineType::BODY, "Written by: Finley Ayers"},
    {HelpLineType::BODY, "Beta Testing by: Lincoln Ayers"},
    {HelpLineType::BODY, "Patience by: Nicci Ayers"},
    {HelpLineType::GAP, nullptr},

};

const int kControlsManualCount = (int)(sizeof(kControlsManual) / sizeof(kControlsManual[0]));